Minor fixes v3
ZunamiLab/ZunamiUI pull request #111
Opened 2022-02-17 15:16 UTC by Avadon

2022-02-19 14:40 UTC, senichevalexey requested changes

2022-02-19 14:40 UTC, senichevalexey commented on src/components/PendingBalance/PendingBalance.scss
> +@import "src/variables";
отвалился притиер?

2022-02-19 14:40 UTC, senichevalexey commented on src/components/PendingBalance/PendingBalance.tsx
> +            <svg className="PendingBalance__icon" width="12" height="14" viewBox="0 0 12 14" fill="none" xmlns="http://www.w3.org/2000/svg">
наверное, было бы хорошей идеей вынести все svg в отдельные файлы и просто импортировать их в переменные

2022-02-19 14:40 UTC, senichevalexey commented on src/components/SideBar/SideBar.tsx
>                      <LinkBlock
ненужное не нужно )))))

2022-02-19 14:40 UTC, senichevalexey commented on src/containers/FinanceOperations.scss
> +@import "src/variables";
двойные кавычки?

2022-02-21 06:45 UTC, Avadon commented on src/components/PendingBalance/PendingBalance.tsx
> +            <svg className="PendingBalance__icon" width="12" height="14" viewBox="0 0 12 14" fill="none" xmlns="http://www.w3.org/2000/svg">
Вынес в переменную, но при таком раскладе иконки будут в папке с компонентом (либо переделывать конфиг webpack'a чтобы давал import за пределами /src). Но вообще мне нравится, когда все что относится к компоненту находится в его папке.

2022-02-21 06:45 UTC, Avadon commented on src/components/SideBar/SideBar.tsx
>                      <LinkBlock
Это временно, чтобы сборка не сломалась. Следующим PR'ом залью Lockdrop, там рефакторинг с учетом новых компонентов + раскоммент этого блока.

2022-02-21 06:46 UTC, Avadon commented on src/components/PendingBalance/PendingBalance.scss
> +@import "src/variables";
Да, забыл на ноуте настроить тоже. Поправил.

2022-02-21 06:46 UTC, Avadon commented on src/containers/FinanceOperations.scss
> +@import "src/variables";
Поправил

2022-02-21 12:22 UTC, senichevalexey requested changes

2022-02-21 12:22 UTC, senichevalexey commented on src/components/InfoBlock/InfoBlock.scss
> +@import "src/variables";
в scss не отработал прититер?

2022-02-21 12:22 UTC, senichevalexey commented on src/components/InfoBlock/InfoBlock.tsx
> +import {useRef, useState} from 'react';
здесь тоже притиер не отработал

2022-02-21 13:29 UTC, Avadon commented on src/components/InfoBlock/InfoBlock.tsx
> +import {useRef, useState} from 'react';
Закоммитил оставшиеся 4 файла с правками по prettier

2022-02-21 13:32 UTC, senichevalexey approved these changes

2022-02-21 13:32 UTC, merged