Minor UI changes
ZunamiLab/ZunamiUI pull request #122
Opened 2022-03-02 10:05 UTC by Avadon

2022-03-03 12:53 UTC, senichevalexey requested changes

2022-03-03 12:53 UTC, senichevalexey commented on src/components/WalletStatus/WalletStatus.tsx
>              console.log('No metamask');
лучше удалять отладочную информацию

2022-03-03 12:53 UTC, senichevalexey commented on src/components/WelcomeCarousel/WelcomeCarousel.tsx
>              console.log('No metamask');
лучше удалять отладочную информацию

2022-03-04 07:25 UTC, Avadon commented on src/components/WalletStatus/WalletStatus.tsx
>              console.log('No metamask');
Исправил след. коммитом

2022-03-04 07:25 UTC, Avadon commented on src/components/WelcomeCarousel/WelcomeCarousel.tsx
>              console.log('No metamask');
Исправил след. коммитом

2022-03-04 08:41 UTC, senichevalexey approved these changes

2022-03-04 08:41 UTC, merged