CSS Changes
ZunamiLab/ZunamiUI pull request #124
Opened 2022-03-17 12:23 UTC by Avadon

2022-03-17 20:14 UTC, senichevalexey requested changes

2022-03-17 20:14 UTC, senichevalexey commented on src/hooks/usePendingOperations.ts
> +    // };
может лучше удалить данный блок?

2022-03-17 20:14 UTC, senichevalexey commented on src/hooks/usePendingOperations.ts
> +                debugger;
ты уверен, что нужно оставлять брейкпоинт?

2022-03-17 20:14 UTC, senichevalexey commented on src/hooks/usePendingOperations.ts
> +                debugger;
ты уверен, что нужно оставлять брейкпоинт?

2022-03-17 20:14 UTC, senichevalexey commented on src/hooks/usePendingOperations.ts
> +            // contract.off(filterWithdraw, withdrawEventHandler);
лучше удалять такие блоки кода

2022-03-17 20:14 UTC, senichevalexey commented on src/sushi/lib/constants.js
> +        3: '0x2ffCC661011beC72e1A9524E12060983E74D14ce',
какие-то странные "магические числа" вместо ключей

2022-03-17 20:14 UTC, senichevalexey commented on src/sushi/lib/constants.js
>          1: '0xe9e7cea3dedca5984780bafc599bd69add087d56',
какие-то странные "магические числа" вместо ключей

2022-03-17 20:14 UTC, senichevalexey commented on src/sushi/utils.js
> +    coinIndex = -1
может заменить данное значение на null, undefined или другое, которое сигнализирует о начальном значении

2022-03-17 20:14 UTC, senichevalexey commented on src/utils/formatbalance.ts
>      return newNumber.dividedBy(BIG_TEN.pow(decimals)).toFixed();
BIG_TEN.pow(decimals) эквивалентно 1е18, может сократить до
return newNumber.dividedBy(1e18).toFixed();

2022-03-18 06:19 UTC, Avadon commented on src/hooks/usePendingOperations.ts
> +    // };
После переделки работы с pending'ами я event'ы закомментил чтобы не потерялись. Надо их переделать, просто пока не добрался разобраться как с ними работать

2022-03-18 06:21 UTC, Avadon commented on src/sushi/lib/constants.js
> +        3: '0x2ffCC661011beC72e1A9524E12060983E74D14ce',
Согласен, просто так уже было изначально. Можно это потом отрефакторить вместе с "sushi" историей.

2022-03-18 06:29 UTC, Avadon commented on src/hooks/usePendingOperations.ts
> +    // };
После переделок работы с pending'ами закомментил куски по event'ы чтобы не потерялись т.к. не успел  разобрался еще как с ними работать

2022-03-18 06:55 UTC, Avadon commented on src/hooks/usePendingOperations.ts
> +                debugger;
Убрал вообще try/catch т.к. по идее тут от них толку нет. Дефолтные значения для deposit/withdraw 0 все равно вернутся если какая-то ошибка будет.

2022-03-18 06:55 UTC, Avadon commented on src/hooks/usePendingOperations.ts
> +                debugger;
Тоже что и выше

2022-03-18 06:55 UTC, Avadon commented on src/hooks/usePendingOperations.ts
> +    // };
Расскомментил и подправил под новый формат pending'ов.

2022-03-22 07:37 UTC, Avadon commented on src/utils/formatbalance.ts
>      return newNumber.dividedBy(BIG_TEN.pow(decimals)).toFixed();
А как тогда записывать в такой форме, учитывая что decimals можно быть любым?

2022-03-22 07:39 UTC, Avadon commented on src/sushi/utils.js
> +    coinIndex = -1
Поменял дефолтное значение на undefined

2022-03-22 07:51 UTC, Avadon commented on src/sushi/lib/constants.js
>          1: '0xe9e7cea3dedca5984780bafc599bd69add087d56',
Предлагаю это в рамках рефакторинга менять

2022-03-22 10:00 UTC, merged