New events structure
ZunamiLab/ZunamiUI pull request #138
Opened 2022-04-04 13:24 UTC by Avadon

2022-04-04 18:58 UTC, senichevalexey requested changes

2022-04-04 18:58 UTC, senichevalexey commented on src/components/Form/Form.tsx
> +                                    type: 'metamask',
я бы не стал хардкодить тип кошелька, так как потом добавятся другие типы

2022-04-04 18:58 UTC, senichevalexey commented on src/components/Form/Form.tsx
> +                                    type: 'metamask',
я бы не стал хардкодить тип кошелька, так как потом добавятся другие типы

2022-04-04 18:58 UTC, senichevalexey commented on src/components/WalletStatus/WalletStatus.tsx
> +            type: 'metamask',
я бы не стал хардкодить тип кошелька, так как потом добавятся другие типы

2022-04-04 18:58 UTC, senichevalexey commented on src/components/WelcomeCarousel/WelcomeCarousel.tsx
> +            type: 'metamask',
я бы не стал хардкодить тип кошелька, так как потом добавятся другие типы

2022-04-05 09:47 UTC, Avadon commented on src/components/Form/Form.tsx
> +                                    type: 'metamask',
Поправил след. коммитом

2022-04-05 09:48 UTC, Avadon commented on src/components/Form/Form.tsx
> +                                    type: 'metamask',
Поправил след. коммитом

2022-04-05 09:48 UTC, Avadon commented on src/components/WalletStatus/WalletStatus.tsx
> +            type: 'metamask',
Поправил след. коммитом

2022-04-05 09:48 UTC, Avadon commented on src/components/WelcomeCarousel/WelcomeCarousel.tsx
> +            type: 'metamask',
Поправил след. коммитом

2022-04-05 09:49 UTC, senichevalexey approved these changes

2022-04-05 09:49 UTC, merged