Typos fix
ZunamiLab/ZunamiUI pull request #139
Opened 2022-04-04 14:13 UTC by Avadon

2022-04-04 19:00 UTC, senichevalexey requested changes

2022-04-04 19:00 UTC, senichevalexey commented on src/components/Header/Header.tsx
> +                        , but it's steel a beta version. Use it at your own risk
steel

2022-04-05 09:07 UTC, Avadon commented on src/components/Header/Header.tsx
> +                        , but it's steel a beta version. Use it at your own risk
Поправил

2022-04-05 09:24 UTC, senichevalexey approved these changes

2022-04-05 09:25 UTC, merged