Fixed NaN error + pending preloader
ZunamiLab/ZunamiUI pull request #90
Opened 2022-01-09 07:05 UTC by Avadon

2022-01-10 12:37 UTC, senichevalexey requested changes

2022-01-10 12:37 UTC, senichevalexey commented on src/components/Form/Form.tsx
> +
наверное, было бы правильным добавить дефолтное значение ошибки в блоке else

2022-01-10 12:37 UTC, senichevalexey commented on src/components/Form/Form.tsx
> +                            }
мы точно не хотим обрабатывать данную ошибку?

2022-01-11 06:23 UTC, Avadon commented on src/components/Form/Form.tsx
> +
А каким оно должно быть? Ведь если ни одно из условий не выполнилось, то и ошибки нет.

2022-01-11 07:30 UTC, Avadon commented on src/components/Form/Form.tsx
> +                            }
Добавил следующим коммитом отображение toast'a с ошибкой:
![Toast!](https://i.ibb.co/pPNX5FM/Screenshot-2022-01-11-at-10-27-12.png "Toast")

2022-01-11 10:34 UTC, Avadon commented on src/components/Form/Form.tsx
> +                            }
Запушил дефолтный текст

2022-01-11 14:30 UTC, senichevalexey approved these changes

2022-01-11 14:31 UTC, merged