Pending deposit fetch
ZunamiLab/ZunamiUI pull request #92
Opened 2022-01-14 12:21 UTC by Avadon

2022-01-19 10:26 UTC, senichevalexey requested changes

2022-01-19 10:26 UTC, senichevalexey commented on src/hooks/usePendingDeposit.ts
> +    const masterChefContract = useMemo(() => {
masterChefContract это сушевский термин

2022-01-19 10:26 UTC, senichevalexey commented on src/hooks/usePendingDeposit.ts
> +        return getContract(ethereum, contractAddresses.masterChef[CHAIN_ID]);
masterChef никак не относится к нашему протоколу )))

2022-01-19 19:40 UTC, Avadon commented on src/hooks/usePendingDeposit.ts
> +        return getContract(ethereum, contractAddresses.masterChef[CHAIN_ID]);
В следующем коммите переименовал название основного контракта. Там в целом и папку /sushi и ряд переменных можно переименовать, но пока не трогал.

2022-01-20 08:15 UTC, senichevalexey approved these changes

2022-01-20 08:15 UTC, merged